site_name: Vincent's wiki
theme: 'journal'
nav:
    - Home: index.md
    - PHP:
      - 'Composer': 'php/composer.md'
      - Laravel:
        - 'Installation': 'php/laravel/Installation.md'
        - 'Homestead': 'php/laravel/Homestead.md'
        - 'Routing': 'php/laravel/Routing.md'
      - Course:
        - '【Laravel道場系列 I】Composer基礎入門與實戰應用': 'php/course/laravel-dojo-composer.md'
        - '【Laravel道場系列 II】Laravel框架簡介及實務展示': 'php/course/laravel-dojo-laravel.md'
        - '【Laravel道場系列 III】PHPUnit測試入門與Laravel測試功能簡介': 'php/course/laravel-dojo-phpunit.md'
    - Git:
      - 'Git 設定': 'git/config.md'
      - 'Git 基礎': 'git/basic.md'
    - Linux 使用手冊:
      - 'Linux 指令': 'linux_shell.md'
    - Document:
      - 'Pandoc': 'document/pandoc.md'
      - 'Easy Markdown with VS Code': 'document/easy-markdown-with-vscode.md'
    - Static Site:
      - 'Mkdocs': 'static-site/mkdocs.md'
      - 'Hexo': 'static-site/hexo.md'