site_name: wiki
pages:
    - Home: index.md
    - About: about.md
    - PHP:
      - 'Composer': 'php/composer.md'
    - Linux 使用手冊:
      - 'Linux 指令': 'linux_shell.md'
    - Course:
      - 'Easy Markdown with VS Code': 'Easy_Markdown_with_VS_Code.md'
theme: 'material'
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
