site_name: Vincent's wiki
theme: 'readable'
nav:
    - Home: index.md
    - 文件:
      - 'Pandoc': 'document/pandoc.md'
      - 'Easy Markdown with VS Code': 'document/easy-markdown-with-vscode.md'
      - Static Site:
        - 'Mkdocs': 'static-site/mkdocs.md'
        - 'Hexo': 'static-site/hexo.md'
    - 必備工具:
      - '常用開發工具': 'dev-tools.md'
      - Git:
        - 'Git 設定': 'git/config.md'
        - 'Git 基礎': 'git/basic.md'
      - 'Linux 指令': 'linux_shell.md'
      - 套件管理:
        - 'Homebrew for mac': 'package-manager/homebrew.md'
        - 'Chocolately for windows': 'package-manager/chocolately.md'
        - 'NPM': 'package-manager/npm.md'
    - PHP:
      - Composer: 'php/composer.md'
      - Laravel:
        - 'Installation': 'php/laravel/Installation.md'
        - 'Homestead': 'php/laravel/Homestead.md'
        - 'Routing': 'php/laravel/Routing.md'
    - AWS:
      - 簡介: 'aws/aws.md'
      - EC2: 'aws/ec2.md'
      - System Manager: 'aws/system-manager.md'
      - CodeDeploy: 'aws/codedeploy.md'
      - CloudWatch: 'aws/cloudwatch.md'