site_name: wiki
theme: 'journal'
nav:
    - Home: index.md
    - PHP:
      - 'Composer': 'php/composer.md'
      - Laravel:
        - 'Installation': 'php/laravel/Installation.md'
        - 'Homestead': 'php/laravel/Homestead.md'
        - 'Routing': 'php/laravel/Routing.md'
      - Course:
        - 'Composer': 'php/course/Composer.md'
        - 'Laravel': 'php/course/Laravel.md'
        - 'PHPUnit': 'php/course/PHPUnit.md'
    - VCS:
      - Git:
        - 'Git 設定': 'vcs/git/config.md'
        - 'Git 基礎': 'vcs/git/basic.md'
    - Linux 使用手冊:
      - 'Linux 指令': 'linux_shell.md'
    - Course:
      - 'Easy Markdown with VS Code': 'Easy_Markdown_with_VS_Code.md'